-- Better Auth tables. Generated by `@better-auth/cli generate` against
-- better-auth 1.7.2; regenerate rather than hand-editing if the version moves.
create table "user" (
  "id" text not null primary key,
  "name" text not null,
  "email" text not null unique,
  "emailVerified" integer not null,
  "image" text,
  "createdAt" date not null,
  "updatedAt" date not null
);

create table "session" (
  "id" text not null primary key,
  "expiresAt" date not null,
  "token" text not null unique,
  "createdAt" date not null,
  "updatedAt" date not null,
  "ipAddress" text,
  "userAgent" text,
  "userId" text not null references "user" ("id") on delete cascade
);

create table "account" (
  "id" text not null primary key,
  "accountId" text not null,
  "providerId" text not null,
  "userId" text not null references "user" ("id") on delete cascade,
  "accessToken" text,
  "refreshToken" text,
  "idToken" text,
  "accessTokenExpiresAt" date,
  "refreshTokenExpiresAt" date,
  "scope" text,
  "password" text,
  "createdAt" date not null,
  "updatedAt" date not null
);

create table "verification" (
  "id" text not null primary key,
  "identifier" text not null,
  "value" text not null,
  "expiresAt" date not null,
  "createdAt" date not null,
  "updatedAt" date not null
);

create index "session_userId_idx" on "session" ("userId");
create index "account_userId_idx" on "account" ("userId");
create index "verification_identifier_idx" on "verification" ("identifier");

-- Documents. Content lives here rather than in object storage: a document is
-- two text fields, so a single owned query loads it and access control is the
-- WHERE clause. Only thumbnails, which are binary, go to R2.
create table "document" (
  "id" text not null primary key,
  "userId" text not null references "user" ("id") on delete cascade,
  "name" text not null,
  "html" text not null,
  "css" text not null,
  -- Set once a thumbnail render has succeeded; null means "show a placeholder",
  -- which is the normal state while the capture is still in flight or after it
  -- failed. Thumbnails must never be able to fail a save.
  "thumbnailUpdatedAt" integer,
  "createdAt" integer not null,
  "updatedAt" integer not null
);

-- Every list query is scoped to one user and ordered by recency.
create index "document_userId_updatedAt_idx" on "document" ("userId", "updatedAt" desc);
